apiVersion: v1
kind: Service
metadata:
  name: green
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: green
  type: ClusterIP     # no need to define

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: red
  labels:
    app: red
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: red
    spec:
      containers:
      - image: viejo/k8s-envoy-demo:red
        name: red
        ports:
        - containerPort: 80
          name: http