apiVersion: v1
kind: Service
metadata:
  name: blue
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: blue
  type: ClusterIP     # no need to define
  
---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: blue
  labels:
    app: blue
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: blue
    spec:
      containers:
      - image: viejo/k8s-envoy-demo:blue
        name: blue
        ports:
        - containerPort: 80
          name: http